import 'dart:ui';

import 'package:flutter_local_smart_notifications/flutter_local_smart_notifications.dart';

/// App-owned notification configuration used by the example application.
///
/// This is intentionally kept outside the package so it is clear that
/// channels, permission copy, and product policy belong to the consuming app.
final expenseNotificationConfig = NotificationConfig(
  enabledProviders: {
    NotificationProvider.localInstant,
    NotificationProvider.localScheduled,
    NotificationProvider.localReminder,
  },
  channels: const [
    NotificationChannelConfig(
      id: 'general',
      name: 'General',
      description: 'General expense notifications',
      importance: ChannelImportance.high,
    ),
    NotificationChannelConfig(
      id: 'reminders',
      name: 'Expense Reminders',
      description: 'Daily and weekly reminders',
      importance: ChannelImportance.max,
    ),
    NotificationChannelConfig(
      id: 'due_dates',
      name: 'Bill Due Dates',
      description: 'Critical bill payment alerts',
      importance: ChannelImportance.max,
      vibrationPattern: [0, 800, 400, 800],
    ),
  ],
  // Generated by flutter_launcher_icons from assets/logo.png. Android uses
  // this resource for both the launcher and the default notification icon.
  androidDefaultIcon: '@mipmap/launcher_icon',
  androidDefaultColor: const Color(0xFFF2F5E8),
  soundAssets: {},
  permissionConfig: const PermissionConfig(
    autoRequestOnInit: false,
    dialogTitle: 'Never Miss a Due Date',
    dialogMessage:
        'Enable notifications to get expense reminders and bill alerts.',
    openSettingsLabel: 'Enable',
    notNowLabel: 'Later',
  ),
  reminderConfig: const ReminderConfig(
    maxActiveReminders: 50,
    persistAcrossReboot: true,
  ),
  logLevel: LogLevel.info,
);
